### ISSUE TITLE
crashing program by restart octoprint server

### ISSUE THREAD

**Issue by AndreRozendaal** [AndreRozendaal/OctoPrintStatus#1]
Traceback (most recent call last):
  File "C:/Users/rozen/PycharmProjects/OctoPrintStatus/main.py", line 8, in <module>
    gui(con)
  File "C:\Users\rozen\PycharmProjects\OctoPrintStatus\gui.py", line 40, in gui
    result = con.get_all()
  File "C:\Users\rozen\PycharmProjects\OctoPrintStatus\connection.py", line 46, in get_all
    error, printer = self.get_printer()
  File "C:\Users\rozen\PycharmProjects\OctoPrintStatus\connection.py", line 34, in get_printer
    return self.get("/printer")
  File "C:\Users\rozen\PycharmProjects\OctoPrintStatus\connection.py", line 31, in get
    return False, json.loads(response)
  File "C:\Users\rozen\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\rozen\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\rozen\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AndreRozendaal** [comment]
added extra exception handling
